version: '3.7'

services: 

  app:
    build: ./docker/web
    working_dir: /usr/share/nginx/site
    volumes:
      - ./:/usr/share/nginx/site
    environment:
      HOME: /home/user
    # user: "1000"

  nginx:
    image: nginx:1.15
    working_dir: /usr/share/nginx/site
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/site
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx

  db:
    image: mariadb
    restart: always
    environment:  
      MYSQL_DATABASE: app_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/databases:/var/lib/mysql
      - ./docker/databases/logs:/var/log/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 6080:8080

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 6081:80

  redis:
    image: redis:alpine
    # volumes:
    #   - ./docker/config/redis/redis.conf:/usr/local/etc/redis/redis.conf