version: '3.7'

services: 

  app:
    build: ./docker/web
    working_dir: /usr/share/nginx/site
    volumes:
      - ./:/usr/share/nginx/site
    environment:
      HOME: /home/user
    # user: "1000"

  nginx:
    image: nginx:1.15
    working_dir: /usr/share/nginx/site
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/site
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/databases:/var/lib/mysql      

  adminer:
    image: adminer
    restart: always
    ports:
      - 6080:8080

  # composer:
  #   image: composer:1.6
  #   volumes:
  #     - ./:usr/share/nginx/site
  #   working_dir: usr/share/nginx/site
  #   command: composer install

  redis:
    image: "redis:alpine"
    # volumes:
    #   - ./docker/config/redis/redis.conf:/usr/local/etc/redis/redis.conf
